### ISSUE TITLE
[request] add support for userthemes / userscripts

### ISSUE THREAD

**Issue by huds0nx** [AlirezaKJ/BetterSoundCloud#11]
I think it would be nice to add support for userscripts/themes. Specifically this soundcloud theme (https://github.com/JunkiEDM/scultradark) makes soundcloud look 100x nicer

**Comment by AlirezaKJ** [comment]
for now i haven't implemented a proper package or theme manager but still there is a custom css section in bsc menu which anyone can put up his own stylesheet, for the style above its not possible to get imported since its officially made for stylus extension and it has some selectors which isn't available at electron webview by default.

but still i can import any themes which are on raw css and userscripts and themes are already supported as i mentioned.

![image](https://github.com/AlirezaKJ/BetterSoundCloud/assets/67480810/3370ba0a-8f07-489e-95d7-88f9a28daec8)
