### ISSUE TITLE
No Settings Option

### ISSUE THREAD

**Issue by OllisJL** [AlirezaKJ/BetterSoundCloud#2]
Hi, I like your client a lot. The only thing is I have Go+ and I can't find the settings menu that's usually shows up when you click your profile. From there I can enable high quality streaming audio so I am unable to do that on your client, or I'm blind.

**Comment by AlirezaKJ** [comment]
yes, since we removed the 3 dot menu from the header bar in the top you can't go to settings page inside the soundcloud webview but we will put an alternative way on patch 0.5.2

how ever you can still navigate to your settings page in BetterSoundCloud using the go-to option from the right-click menu by entering the setting page url https://soundcloud.com/settings
